### ISSUE TITLE
when testing with -r uvu sometimes program never exits

### ISSUE THREAD

**Issue by Gozala** [hugomrdias/playwright-test#204]
**Describe the bug**

Running something like `playtright-test -r uvu test/web.spec.js` sometimes never exits despite the fact that test are finished and output is printed into stdout.

**To Reproduce**
Here is the case where it kept hanging & I was able to reproduce it locally as well.
https://github.com/web-std/io/pull/2/checks?check_run_id=2560237017

**Additional context**
After some digging I figured out that problem is caused by the fact that `console` listener never ran

https://github.com/hugomrdias/playwright-test/blob/7419f7e24b1a49025a320aec2150901332b143ba/src/runner-uvu.js#L23-L33

As far as I can tell that is because test run was complete sooner than listener was registered. If I make a test await for a single tick things seem to work as expected. Given that output is printed into stdout I wonder if there is a better way to hook into this to make things more reliable.

**Comment by hugomrdias** [comment]
damn, uvu doesnt have a better option to hook into the test suite cycle .. im gonna try to see if i can improve this in some way
