### ISSUE TITLE
How to report coverage to codecov?

### ISSUE THREAD

**Issue by yisar** [hugomrdias/playwright-test#244]
Since I use zora, `--cov`  is invalid. What can I do? This is my repo:
https://github.com/yisar/fre/blob/master/package.json

**Comment by hugomrdias** [comment]
<img width="546" alt="Screenshot 2021-07-06 at 12 58 25" src="https://user-images.githubusercontent.com/314190/124596216-ec216800-de59-11eb-8975-47cf576abc56.png">

Seems to work, why did you think --cov is invalid ?

**Comment by yisar** [comment]
Thank you very much! I works well now, It could be my fault.
