### ISSUE TITLE
Support bundling `expect`

### ISSUE THREAD

**Issue by PaperStrike** [hugomrdias/playwright-test#295]
**Is your feature request related to a problem? Please describe.**
I always wanted to write tests with Jest's [`expect`](https://www.npmjs.com/package/expect) package, while it is not officially supported to do so.

**Describe the solution you'd like**
It would be GREAT to see [`expect`](https://www.npmjs.com/package/expect) running in real browser unit tests.

**Describe alternatives you've considered**
I came across [`@storybook/expect`](https://www.npmjs.com/package/@storybook/expect) when looking for a working browser `expect`, and noticed that it happens by bundling with `node-polyfill-webpack-plugin` (which has an equivalent [`@esbuild-plugins/node-globals-polyfill`](https://www.npmjs.com/package/@esbuild-plugins/node-globals-polyfill) in esbuild) and resolving `graceful-fs` to `fs`. (see their repo [here](https://github.com/storybookjs/expect))

- For the bundling, I created a branch [third-party-polyfill-inject](https://github.com/PaperStrike/playwright-test/tree/third-party-polyfill-inject) in my fork. It doesn't have to find which node builtin should be polyfilled in each runner since then.
- Now the problem comes to the `graceful-fs` resolution. If you, the author, agrees to directly resolve it to `fs`, I would be glad to write that in another branch then. And there are other approaches, like making it a cli option, introducing new runners like `mocha+expect`, etc.

I would like to hear your opinions.

This tool is great, thank you!

**Additional context**
`expect` is what the official [Playwright Test](https://playwright.dev/docs/intro) uses, too. Together with my [playwright-fixtures](https://github.com/PaperStrike/playwright-fixtures), it is quite funny to see "the offical test runner" supports both e2e and unit tests.

**Comment by hugomrdias** [comment]
we can add custom esbuild config with a config file https://github.com/hugomrdias/playwright-test/blob/master/readme.md#config 

```js
module.exports = {
  buildConfig: {
    plugins: [
        NodeModulesPolyfills(),
        GlobalsPolyfills({
            process: true,
            buffer: true,
            define: { 'process.env.var': '"hello"' }, // inject will override define, to keep env vars you must also pass define here https://github.com/evanw/esbuild/issues/660
        }),
    ]
  },
}
```

Note that config file needs to be commonjs for now

**Comment by hugomrdias** [comment]
im closing this issue, please re-open if the solution above doesnt work.
Note: i improve the readme a bit around this.
