### ISSUE TITLE
Invalid package `exports` field

### ISSUE THREAD

**Issue by PaperStrike** [hugomrdias/playwright-test#330]
**Describe the bug**
Currently the package `exports` field

https://github.com/hugomrdias/playwright-test/blob/f35101c8bd75a024e18c50965d4684e0e023f0b8/package.json#L11

points to a file that doesn't exist. As the `main` field points well, is it an oversight?

**Comment by hugomrdias** [comment]
yes its an oversight, can you sent a PR with a fix please.
