### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by achingbrain** [hugomrdias/playwright-test#43]
What's the plan for getting coverage information out of this test runner?

I ran the following but got empty reports:

```console
$ nyc --reporter html --reporter lcov playwright-test
```

and trying to fit `nyc` into the `--runner` value fails with `TypeError: object null is not a constructor`

**Comment by hugomrdias** [comment]
Cov needs to be integrated directly into the bundler,there's a webpack plugin that instruments the code and outputs the files like nyc

**Comment by hugomrdias** [comment]
refs:

https://github.com/istanbuljs/puppeteer-to-istanbul

https://github.com/puppeteer/puppeteer/pull/6454

https://github.com/istanbuljs/v8-to-istanbul

**Comment by hugomrdias** [comment]
![Uploading Screenshot 2020-11-08 at 19.59.20.png…]()
