### ISSUE TITLE
Support for vitest

### ISSUE THREAD

**Issue by hetsch** [hugomrdias/playwright-test#431]
Hi,

I'm currently using vitest (https://vitest.dev) for my unittests and wanted to ask if you might consider supporting this test framework. 
It seems that vitest is getting more popular in the Vue/React community.

Thank's a lot!

**Comment by hugomrdias** [comment]
vitest is a full blown test framework that runs only in node, support is impossible! You should not use those if you want to test code that runs in the browser.
