### ISSUE TITLE
Prevent zora test window from closing on error

### ISSUE THREAD

**Issue by theSherwood** [hugomrdias/playwright-test#467]
**Is your feature request related to a problem? Please describe.**
I'm using playwright-test to run zora tests. When there is an error, the playwright process exits. I would like it to stay open and try again as code changes.

**Describe the solution you'd like**
If there were some cli flag to tell the playwright to keep the process running even through errors, that would be great.

**Describe alternatives you've considered**
Maybe there's a sensible way to run the playwright process with nodemon, though that means that when run in `--debug`, the browser window will be opening and closing repeatedly.

Thanks for this library, by the way. It's great!

**Comment by hugomrdias** [comment]
Feel free to re open if this still happens.

Thank you 🙏🏼
