### ISSUE TITLE
Update playwright-core version to support Ubuntu 22.04

### ISSUE THREAD

**Issue by birtles** [hugomrdias/playwright-test#505]
GitHub actions are updating their `ubuntu-latest` image to Ubuntu 22.04 ([announcement](https://github.com/actions/runner-images/issues/6399)).

It appears that `playwright-test` currently depends on `playwright-core` version 1.22.1 ([source](https://github.com/hugomrdias/playwright-test/blob/ec13db238b280fa9d81a6d760d2a07eff9e05186/package.json#L67)).

However, it looks like playwright only supports Ubuntu 22.04 as of Playwright 1.25.0 ([release](https://github.com/microsoft/playwright/releases/tag/v1.25.0)).

As a result, attempting to install playwright using `npx playwright install --with-deps` in a GitHub action workflow based on `ubuntu-latest` will fail since it will attempt to use the playwright version from `playwright-test`.

Errors such as the following:

```
Get:27 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [57.8 kB]
Fetched 4470 kB in 1s (3728 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

Package libicu66 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

Once can force the playwright version to install to 1.28.0 using `npx playwright@^1.28.0 install --with-deps` and then the playwright install will succeed, but webkit tests will fail since `playwright-test` will download Webkit 15.4 (since that is the version used by playwright-core 1.22.1) and discover it is missing some dependencies.

Any chance `playwright-test` could update the playwright-core version to 1.28.0 (or make it a peer dependency / not pin the version?)

**Comment by hugomrdias** [comment]
v8.1.2 should fix this, let me know if it doesnt. 

thank you

**Comment by birtles** [comment]
Thanks! Works for me!
