### ISSUE TITLE
Support tinybench

### ISSUE THREAD

**Issue by achingbrain** [hugomrdias/playwright-test#529]
It would be great if this supported [tinybench](https://www.npmjs.com/package/tinybench) - it's like benchmark.js but is maintained and has decent promise support, along with extension points for test setup and teardown.

**Comment by hugomrdias** [comment]
you can actually just run it with the default runner

```js

// ./cli.js mocks/tinybench.js
import { Bench } from 'tinybench'

const bench = new Bench({ time: 100 })

bench
  .add('switch 1', () => {
    let a = 1
    let b = 2
    const c = a
    a = b
    b = c
  })
  .add('switch 2', () => {
    let a = 1
    let b = 10
    a = b + a
    b = a - b
    a = b - a
  })

async function main() {
  await bench.run()

  console.table(
    bench.tasks.map(({ name, result }) => ({
      'Task Name': name,
      'Average Time (ps)': result?.mean * 1000,
      'Variance (ps)': result?.variance * 1000,
    }))
  )
}

main()
```

**Comment by hugomrdias** [comment]
done https://github.com/hugomrdias/playwright-test/commit/d2054238b6ecc74117676a7b1a0a4f4eebc929a7 theres a new runner `none` that just runs code and stops supports globs, debug, watch etc..
