### ISSUE TITLE
ESM Worker support

### ISSUE THREAD

**Issue by talentlessguy** [hugomrdias/playwright-test#530]
**Is your feature request related to a problem? Please describe.**

I'm porting a library to ESM and have a test suite in workers, for it to work I need to be able to pass `type: "module"` to a worker. module environment will allow to use `import.meta.url`

**Describe the solution you'd like**

A `--type` flag with either `classic` or `module` (as in [Web API](https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker)) which will do `Worker("${filePath}", { type: "${workerType}" })`

**Describe alternatives you've considered**

Since Worker creation is [hardcoded](
https://github.com/hugomrdias/playwright-test/blob/master/src/utils/index.js#L270-L279) there's no way to pass any options at all

**Comment by hugomrdias** [comment]
https://github.com/hugomrdias/playwright-test/commit/e7bde86b161f950d9fc1587ad2feb50683df790f will be on npm as v9
