### ISSUE TITLE
Access context from test

### ISSUE THREAD

**Issue by YousefED** [hugomrdias/playwright-test#540]
I'd like to set the Host browser to offline, using for example https://playwright.dev/docs/api/class-browsercontext#browser-context-set-offline.

As far I understand, this is currently not possible right? I.e.: I can only set options in a config, but can't access them during a test execution? Do you think this might be feasible?

**Comment by hugomrdias** [comment]
maybe with https://playwright.dev/docs/api/class-browsercontext#browser-context-expose-binding
