### ISSUE TITLE
Some way to read contents of non-js files

### ISSUE THREAD

**Issue by Gozala** [hugomrdias/playwright-test#544]
**Is your feature request related to a problem? Please describe.**

When working with test data sets it is common to encounter them in .csv or some binary format. Unfortunately it is impossible to use such datasets without compiling them into some module ahead of time, which is a significant downside as keeping test up to date with datasets incur extra barriers.

**Describe the solution you'd like**

Ideally we would have some universal way through `import` syntax or perhaps via `fetch` API or maybe even a custom module to load contents of arbitrary files that will work across standard node runtime and playwright tests.

**Describe alternatives you've considered**

- Tried using `fetch`, pasing `--extensions csv` flag, using fs module but non of them work.
- generating dummy js files that simply export string of content, this works but is a pain to maintain also things get out of date frequently.

**Comment by hugomrdias** [comment]
can't you just pass `--assets <path to folder with csv>` and `fetch` in the tests ?

**Comment by Gozala** [comment]
Here is an example code

```js
const url = new URL('./vector.csv', import.meta.url)
const vector = await fetch(url.href).then($ => $.text())
// ...
```

Above will work in nodejs, however not in playwright-test where I'll get following

```js
Loading http://127.0.0.1:64524/vector.csv
Failed to load resource: the server responded with a status of 404 (Not Found)
```

That is because `import.meta.url` ends up something like `http://127.0.0.1:64524/bundle-out.js` regardless of the actual module path, which in turn makes it impossible to have a universal way to do it.

**Comment by hugomrdias** [comment]
Ah so the problem is the value in import.meta.url Humm. This is going to be hard probably impossible. Because of the bundling. 
I would suggest changing to a cwd relative URLs instead of current file relative. 

You can even use pw test to run both browser and node there's a new mode `node` to bundle and run in node. Don't ask me why but I actually find it useful in typescript code bases...

**Comment by Gozala** [comment]
Maybe we could integrate https://www.npmjs.com/package/@chialab/esbuild-plugin-meta-url to address this problem

**Comment by Gozala** [comment]
That plugin did not end up working for me [but following seem to do the job](https://github.com/web3-storage/data-segment/blob/feat/aggregate-commp/.pw-testrc.js)

```js
export default {
  buildConfig: {
    plugins: [
      {
        name: 'import.meta.url',
        setup({ onLoad }) {
          onLoad({ filter: /\.js|\.ts/, namespace: 'file' }, (args) => {
            let code = FS.readFileSync(args.path, 'utf8')
            code = code.replace(
              /new URL\((.*), import\.meta\.url\)/g,
              `new URL(\$1, ${JSON.stringify(pathToFileURL(args.path))})`
            )
            return { contents: code }
          })
        },
      },
    ],
  },
}
```

@hugomrdias how do you feel about including something along the same lines so that things would work out of the box ? Ideally we'd also tap into fetch requests resolved URIs through [route](https://playwright.dev/docs/api/class-route) API and will respond with corresponding files

**Comment by hugomrdias** [comment]
the latest `playwright-test/client` has the server url exported 
```js
import * as Client from 'playwright-test/client'
const url = new URL('./vector.csv', Client.server)
const vector = await fetch(url.href).then($ => $.text())

```

running `pw-test --assets <path-to-files>` you can fetch in browser and node.
