### ISSUE TITLE
Update to 1.35 playwright-core possible?

### ISSUE THREAD

**Issue by martenrichter** [hugomrdias/playwright-test#545]
Thank you for your nice testing framwork!

I have a pending pull request on my project using it: 
https://github.com/fails-components/webtransport/pull/130

However, the test suffered from some severe flackyness.
As it turned out it was caused by segmentation faults in chromium's network service handling webtransport.
The bug was fixed in 115 of chromium, as playwrigth-core was just updated to support this version.
I would like to ask , if it is possible to release a new version with the updated playwrigth-core version 1.35 .
Thanks!

**Comment by achingbrain** [comment]
@hugomrdias what do you think?

**Comment by martenrichter** [comment]
Thanks!
