### ISSUE TITLE
pass environment variables to runtime

### ISSUE THREAD

**Issue by YousefED** [hugomrdias/playwright-test#549]
**Is your feature request related to a problem? Please describe.**
In Vite, I can access environment variables (for example, set in `.env.development` via `import.meta.env`.

When playwright-test builds my project, I can't access these variables

**Describe the solution you'd like**
Have a way to pass env variables to code run via playwright-test.

**Comment by hugomrdias** [comment]
you have process.env available with all the cli env vars, do you require import.meta.env specifically ?
