### ISSUE TITLE
Add quiet mode

### ISSUE THREAD

**Issue by bgins** [hugomrdias/playwright-test#571]
**Is your feature request related to a problem? Please describe.**

`playwright-test` emits messages like `[playwright-test] Autodetected "mocha" as the runner.`. These messages are great in interactive mode, but can end up in reporting when output redirecting to a file.

For example:

```
pw-test test/test.js --reporter json --mode node > test/report/node.json
```

may include an autodetection message in `node.json`.

**Describe the solution you'd like**

Add a `quiet` mode that only emits reporter results.

**Describe alternatives you've considered**

For the autodetection message, it is possible to explicitly set a runner with `-r mocha` to avoid the autodetection message.

**Comment by hugomrdias** [comment]
all logs not from tests go to stderr not stdout now.
