### ISSUE TITLE
autodetect fail with describe.only

### ISSUE THREAD

**Issue by hugomrdias** [hugomrdias/playwright-test#572]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by achingbrain** [comment]
I'm seeing something similar with `.skip`, it might be the same problem:

```
TypeError: Cannot read properties of null (reading 'callee')
     at detectTestRunner (file:///app/node_modules/playwright-test/src/utils/auto-detect.js:38:33)
    at file:///app/node_modules/playwright-test/cli.js:277:16
Command failed with exit code 1: pw-test test/**/*.spec.{js,cjs,mjs} test/browser.{js,cjs,mjs} dist/test/**/*.spec.{js,cjs,mjs} dist/test/browser.{js,cjs,mjs} --mode main --config /app/node_modules/aegir/src/config/pw-test.js --browser chromium --timeout=60000
```

https://github.com/libp2p/js-libp2p/actions/runs/5670622461/job/15367537329?pr=1900
