### ISSUE TITLE
Update to 1.38 playwright-core possible?

### ISSUE THREAD

**Issue by martenrichter** [hugomrdias/playwright-test#587]
Hi,
again thanks for your testing framework!

I have a pending pull request on my project using it:
https://github.com/fails-components/webtransport/pull/130

It initially suffered from one bug in Chromium, which was fixed afterward, and you were so kind to update your playwright-test and then to use the fixed browser.
Of course, as always I found a second webtransport-related bug in Chromium and I also patched it, it arrived in version 117.
So it would be really nice if you could update to version 1.38 of the playwright-core package.
I hope it will be the last bug in chromium, that is blocking this PR...

**Comment by hugomrdias** [comment]
12.3.4 should have that

**Comment by martenrichter** [comment]
Thanks!
