### ISSUE TITLE
console.time/timeEnd throwing No such label warning

### ISSUE THREAD

**Issue by haydenyoung** [hugomrdias/playwright-test#619]
**Describe the bug**
When running console.time/console.timeEnd, the following warning is reported and I am unable to successfully time tasks:

```
(node:675331) Warning: No such label 'test: 0.0009765625 ms' for console.timeEnd()
```

It appears the label that timeEnd expects changes from "label" to "label <execution-time> ms".

I am running playwright-test with mocha tests.

**To Reproduce**

Create a simple test:

```
describe('Test', () => {
  it('time/timeEnd', () => {
    console.time('test')
    console.timeEnd('test')
  })
})
```

Run the test on the cmd line:

```
./node_modules/.bin/playwright-test test/index.js --runner mocha
```

Output is:
```
(node:675331) Warning: No such label 'test: 0.0009765625 ms' for console.timeEnd()
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Expected behavior**
Task time should be correctly displayed:

```
test: 0.08ms
```

**Additional context**
- Playwright v12.6.0

- Running test in mocha results in correct output

- Running test using --debug (displaying browser window) and viewing console in browser window shows correct output

- This problem only occurs in the terminal (I.e. cmd line output).

**Comment by hugomrdias** [comment]
hey @haydenyoung this should be fixed here https://github.com/hugomrdias/playwright-test/commit/6cf6f6e8b6713dc3df216d189e839dd1e0481fbd
